import {addWaveA,labels,loadWaveA,removeWaveA,totals,updateWaveA,type WaveAItem,type WaveAState,type WaveAType} from './store.js';
const esc=(v:unknown)=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]??c));
let state:WaveAState=loadWaveA();let active:WaveAType='project';
const launch=document.createElement('button');launch.className='wave-a-launch';launch.textContent='Vague A';
const modal=document.createElement('div');modal.className='wave-a-modal';modal.hidden=true;modal.innerHTML='<section class="wave-a-shell"><div id="wave-a-root"></div></section>';
document.body.append(launch,modal);launch.onclick=()=>{modal.hidden=false;render()};modal.addEventListener('click',e=>{if(e.target===modal)close();const el=(e.target as HTMLElement).closest<HTMLElement>('[data-wa]');if(!el)return;const action=el.dataset.wa;if(action==='close')close();if(action==='tab'){active=el.dataset.type as WaveAType;render()}if(action==='delete'&&el.dataset.id&&confirm('Supprimer cet élément ?')){state=removeWaveA(state,el.dataset.id);render()}if(action==='toggle'&&el.dataset.id){const item=state.items.find(i=>i.id===el.dataset.id);if(item){state=updateWaveA(state,item.id,{status:item.status==='done'?'active':'done'});render()}}});modal.addEventListener('submit',e=>{const form=e.target as HTMLFormElement;if(form.id!=='wa-form')return;e.preventDefault();const d=new FormData(form);const amount=Number(d.get('amount')||0);const progress=Math.max(0,Math.min(100,Number(d.get('progress')||0)));state=addWaveA(state,{type:active,title:String(d.get('title')||'').trim(),amount:active==='transaction'?amount:undefined,date:String(d.get('date')||''),status:'active',category:String(d.get('category')||''),notes:String(d.get('notes')||''),progress:active==='project'?progress:undefined});form.reset();render()});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='a'){e.preventDefault();modal.hidden=false;render()}if(e.key==='Escape'&&!modal.hidden)close()});
function close(){modal.hidden=true}
function render(){const root=modal.querySelector<HTMLElement>('#wave-a-root');if(!root)return;const t=totals(state);root.innerHTML=`<header><div><small>QUOTIDIEN V7</small><h1>Vague A en production</h1><p>Projets, finances, documents, maison et automatisations réunis dans un tableau de bord spécialisé.</p></div><button data-wa="close">×</button></header><section class="wa-kpis"><article><strong>${t.projects}</strong><span>projets · ${t.avg}% moyen</span></article><article><strong>${fmt(t.balance)}</strong><span>solde suivi</span></article><article><strong>${t.documents}</strong><span>documents</span></article><article><strong>${t.assets}</strong><span>équipements</span></article><article><strong>${t.automations}</strong><span>règles</span></article></section><nav>${(Object.entries(labels) as [WaveAType,string][]).map(([id,label])=>`<button data-wa="tab" data-type="${id}" class="${active===id?'active':''}">${label}</button>`).join('')}</nav>${form(active)}<section class="wa-list">${items(active)}</section>`}
function form(type:WaveAType){const specifics=type==='transaction'?'<input name="amount" type="number" step="0.01" placeholder="Montant (+ revenu, - dépense)">':type==='project'?'<input name="progress" type="number" min="0" max="100" placeholder="Progression %">':'';return `<form id="wa-form"><input name="title" placeholder="${placeholder(type)}" required><input name="category" placeholder="Catégorie / dossier"><input name="date" type="date">${specifics}<textarea name="notes" placeholder="Notes, prochaine étape, contexte…"></textarea><button>Ajouter</button></form>`}
function placeholder(type:WaveAType){return({project:'Nouveau projet de vie',transaction:'Nouvelle opération financière',document:'Nouveau document ou échéance',asset:'Nouvel équipement ou entretien',automation:'Nouvelle règle automatique'})[type]}
function items(type:WaveAType){const list=state.items.filter(i=>i.type===type);if(!list.length)return'<div class="wa-empty">Aucun élément. Le module est prêt.</div>';return list.map(card).join('')}
function card(i:WaveAItem){return `<article class="wa-item ${i.status==='done'?'done':''}"><div><strong>${esc(i.title)}</strong><span>${esc(i.category||'Sans catégorie')}${i.date?` · ${esc(i.date)}`:''}</span>${i.notes?`<p>${esc(i.notes)}</p>`:''}${i.type==='transaction'?`<b>${fmt(i.amount??0)}</b>`:''}${i.type==='project'?`<progress max="100" value="${i.progress??0}"></progress><small>${i.progress??0}%</small>`:''}</div><footer><button data-wa="toggle" data-id="${i.id}">${i.status==='done'?'Réactiver':'Terminer'}</button><button data-wa="delete" data-id="${i.id}">Supprimer</button></footer></article>`}
function fmt(v:number){return new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(v)}
